language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: Xe1kTL0Xpkc9gvT08tIQ1jxa5xix9TC0bKZF7jyrXf8PUQ3qEOOG6k7xguinPB+bGrxylmUQfYnMV1we13VbaEhnKMdSigZf7MDJfyaUx/57+Gsy9Wbn89aGqMlkspfOgtZAkVR74KEZwldGXQpHCbDCtZh3MfumnRC9LQYVqGLdOJ1wXQhwIzhYx1f8s53dQoBjAI7SlYcQBrDossAwmW4cWN+oerD9EQps7bGzm4I9KUbHdul3zAL3ZCrVTb5Xz3wRPHydw7uOmmLOmHADEvSX/dLBc5NQTibsnlGEDdHRkFig0TnfvaKez8GtAZ6TGTKY+/6gigds5dtpuw5767dNKx/jSESBRt1uySvwc3G/tsHlzBt7gx9DOODnU/ECcHDN6cXZyZmtD4Y12wP/ux33t4vG4yfEs/j5YKrrG7qWBSwNfYQs0gCLT51uLKAb1dxLJjR8vT9dZYI30foVt/CLJmsuojcJ5r+RW2rn8h4rHcrP+xNSjXk44WBJoxnmoYSJyv9Kx6SloBWiFwyFW4HvFedE0rgKoOrJqebf9ZYlgHnsfqDoCytZ3XcWlRerO6wmJ5jLNfcDNuSbtGIx/GDO4cMvlwzlkkUt+EWcSOvE8IJhnmH7xcijVJ+JX7Z9c9dxygt7D4Uz/FzEYpDDZpXSsSWGpofhzErkLyp5+ZQ=
  app: sleepy-sierra-43686
  on:
    repo: eoneill23/mockr
