language: node_js
node_js: 
- node

deploy:
  provider: heroku
  api_key:
    secure: PBJR1NZNp55vtfkTzWWWXwnUcgHz96jOvcHqnN4VpugjhR8N75oKpYuXqYeF49A103+wz25fGbu5kHu3MhcSegKpCdX7YTBZAskBwifLdSwmFB6NvBvebQZp+SD4GNFvxvcD2uY9dXO1Ue3O2s9uwsOLEiJL27wrGXzvWEdh6pi1QbLlSdE3FxfszPmd9uAP9iFZ6W5antU8QROQUvHWl935vkyNxRYsplFiYbWuc86nQJaM9wC5LFRVWQaAGNGtPOfLzp1jDV68NzTMU/1VyimEA3wtDqlcGnEEbY39uZFsYoNG6nAqyKGSLTAhaumXNz9PNJ5Bx9mRCAd4EhOmmuSAeL6XRIebyZLbCQl3xqbQuwztLinAGQ/oaseiUKMIRT4tT1u6zORvZUoq4p4EQShaN+aFib/sm696Eq4blAoBRZgsUUfVxX2lKRZO7Cdnxq8FCkymKhouey7JIhMRDvLN1X8Pi71fKAIALQ89Cgz8Jz01XzEy9lcDkf8U1FHwpzmf3ZiubZBgUf6XDOdRpeMcFeL/0RsK0nFObhKDNnUsNHPcClKZZlKAZbHnwTQxFOxURKAjD1z1Krr5d3rHbXbBOt2UOi0RYT9N0WErm4QF7NNEBU1KeQ/eK87awFR7oyMdcRdMZNcB1o0W5fd0d5gTQcSPxLp39IRzcS0bti8=
  app: sleepy-sierra-43686
  on:
    repo: eoneill23/mockr